import Navbar from '@/components/global/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import Footer from '@/components/global/Footer';
import { configureStore } from '@reduxjs/toolkit';
import cartReducer from '@/state/index';
import { Provider } from 'react-redux';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const store = configureStore({
	reducer: {
		cart: cartReducer,
	},
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<Provider store={store}>
					<Navbar />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
